import { useEffect, useState } from 'react'
import { Plus, X } from 'lucide-react'
import { PageHeader } from '../shared/PageHeader'
import { supabase } from '../../../lib/supabase'
import { formatDate } from '../../exportUtils'
import type { AppUser } from '../../types'

type Beneficiary = { id: string; guardian_name: string; baby_name: string; nicu_eligible: boolean }
type Bottle = { id: string; bottle_number: string | null; remaining_volume_ml: number; batches?: { batch_number: string | null } | null }
type Dispense = { id: string; volume_ml: number; total_fee: number; dispensed_at: string | null; beneficiaries?: Beneficiary | null }
export function DispensingScreen({ user }: { user: AppUser }) {
  const [rows, setRows] = useState<Dispense[]>([]); const [beneficiaries, setBeneficiaries] = useState<Beneficiary[]>([]); const [bottles, setBottles] = useState<Bottle[]>([]); const [open, setOpen] = useState(false)
  async function load(): Promise<void> { const [{ data: disp }, { data: bens }, { data: bots }] = await Promise.all([supabase.from('dispensing_records').select('id,volume_ml,total_fee,dispensed_at,beneficiaries(id,guardian_name,baby_name,nicu_eligible)').order('dispensed_at', { ascending: false }), supabase.from('beneficiaries').select('id,guardian_name,baby_name,nicu_eligible').eq('nicu_eligible', true), supabase.from('bottles').select('id,bottle_number,remaining_volume_ml,batches(batch_number)').eq('status', 'available').gt('remaining_volume_ml', 0)]); setRows((disp ?? []) as Dispense[]); setBeneficiaries((bens ?? []) as Beneficiary[]); setBottles((bots ?? []) as Bottle[]) }
  useEffect(() => { void load() }, [])
  async function save(event: React.FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const form = new FormData(event.currentTarget); const volume = Number(form.get('volume_ml')); const bottle = bottles.find((b) => b.id === String(form.get('bottle_id'))); const { data } = await supabase.from('dispensing_records').insert({ beneficiary_id: String(form.get('beneficiary_id')), status: 'confirmed', volume_ml: volume, fee_per_ml: 2, bottle_deposit_amount: 0, deposit_paid: true, clinical_abstract_verified: true, prescription_verified: true, cooler_with_ice_verified: true, dispensed_at: new Date().toISOString() }).select('id').single(); if (data && bottle) { await supabase.from('dispensing_items').insert({ dispensing_record_id: data.id, bottle_id: bottle.id, volume_ml: volume }); await supabase.from('bottles').update({ remaining_volume_ml: Math.max(0, bottle.remaining_volume_ml - volume), status: bottle.remaining_volume_ml - volume <= 0 ? 'dispensed' : 'available' }).eq('id', bottle.id) } setOpen(false); await load() }
  return <div><PageHeader crumbs={[{ label: 'Operations' }]} title="Dispensing" subtitle="Supabase-backed milk release records" actions={<button onClick={() => setOpen(true)} className="flex items-center gap-2 px-4 py-2 text-sm text-white rounded-lg" style={{ background: '#eea4bb' }}><Plus className="w-4 h-4" />New Dispensing</button>} />
    <div className="bg-white rounded-2xl border overflow-x-auto"><table className="w-full"><thead><tr>{['Recipient','Baby','Volume','Total Fee','Dispensed By','Date'].map((h) => <th key={h} className="px-4 py-3 text-left text-xs text-[#6B7280]">{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t"><td className="px-4 py-3 text-sm">{row.beneficiaries?.guardian_name}</td><td className="px-4 py-3 text-sm">{row.beneficiaries?.baby_name}</td><td className="px-4 py-3 text-sm">{row.volume_ml}</td><td className="px-4 py-3 text-sm">PHP {row.total_fee}</td><td className="px-4 py-3 text-sm">{user.name}</td><td className="px-4 py-3 text-sm">{formatDate(row.dispensed_at)}</td></tr>)}</tbody></table></div>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40"><form onSubmit={save} className="w-full max-w-md bg-white rounded-xl p-6 space-y-4"><div className="flex justify-between"><h2 className="font-semibold">New Dispensing</h2><button type="button" onClick={() => setOpen(false)}><X className="w-4 h-4" /></button></div><select name="beneficiary_id" required className="w-full border rounded-lg px-3 py-2">{beneficiaries.map((b) => <option key={b.id} value={b.id}>{b.guardian_name} - {b.baby_name}</option>)}</select><select name="bottle_id" required className="w-full border rounded-lg px-3 py-2">{bottles.map((b) => <option key={b.id} value={b.id}>{b.bottle_number} / {b.batches?.batch_number} - {b.remaining_volume_ml} mL</option>)}</select><input name="volume_ml" type="number" min="1" required className="w-full border rounded-lg px-3 py-2" placeholder="Volume mL" /><button className="w-full rounded-lg py-2 text-white" style={{ background: '#eea4bb' }}>Confirm Dispensing</button></form></div>}
  </div>
}