import { useEffect, useState } from 'react'
import { Plus, X } from 'lucide-react'
import { PageHeader } from '../shared/PageHeader'
import { StatusBadge } from '../shared/StatusBadge'
import { supabase } from '../../../lib/supabase'
import { formatDate, toTitle } from '../../exportUtils'

type Beneficiary = { id: string; guardian_name: string; baby_name: string; nicu_eligible: boolean }
type Inquiry = { id: string; inquiry_type: string; status: string; requested_at: string; nicu_confirmed: boolean; beneficiaries?: Beneficiary | null }
export function InquiryWaitingListScreen() {
  const [rows, setRows] = useState<Inquiry[]>([]); const [beneficiaries, setBeneficiaries] = useState<Beneficiary[]>([]); const [open, setOpen] = useState(false)
  async function load(): Promise<void> { const [{ data: inq }, { data: bens }] = await Promise.all([supabase.from('inquiries').select('id,inquiry_type,status,requested_at,nicu_confirmed,beneficiaries(id,guardian_name,baby_name,nicu_eligible)').order('requested_at', { ascending: false }), supabase.from('beneficiaries').select('id,guardian_name,baby_name,nicu_eligible').order('guardian_name')]); setRows((inq ?? []) as Inquiry[]); setBeneficiaries((bens ?? []) as Beneficiary[]) }
  useEffect(() => { void load() }, [])
  async function save(event: React.FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const form = new FormData(event.currentTarget); const beneficiary = beneficiaries.find((b) => b.id === String(form.get('beneficiary_id'))); await supabase.from('inquiries').insert({ beneficiary_id: String(form.get('beneficiary_id')), inquiry_type: String(form.get('inquiry_type')), status: 'waiting', nicu_confirmed: beneficiary?.nicu_eligible ?? false, notes: String(form.get('notes') ?? '') }); setOpen(false); await load() }
  async function advance(row: Inquiry): Promise<void> { const next = row.status === 'waiting' ? { status: 'notified', notified_at: new Date().toISOString() } : row.status === 'notified' ? { status: 'fulfilled', fulfilled_at: new Date().toISOString() } : null; if (next) { await supabase.from('inquiries').update(next).eq('id', row.id); await load() } }
  return <div><PageHeader crumbs={[{ label: 'Recipients' }]} title="Inquiry & Waiting List" subtitle="Supabase-backed inquiry queue" actions={<button onClick={() => setOpen(true)} className="flex items-center gap-2 px-4 py-2 text-sm text-white rounded-lg" style={{ background: '#eea4bb' }}><Plus className="w-4 h-4" />Log Inquiry</button>} />
    <div className="bg-white rounded-2xl border overflow-x-auto"><table className="w-full"><thead><tr>{['Recipient','Baby','NICU','Type','Date','Status','Action'].map((h) => <th key={h} className="px-4 py-3 text-left text-xs text-[#6B7280]">{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t"><td className="px-4 py-3 text-sm">{row.beneficiaries?.guardian_name}</td><td className="px-4 py-3 text-sm">{row.beneficiaries?.baby_name}</td><td className="px-4 py-3"><StatusBadge value={row.nicu_confirmed ? 'NICU' : 'Non-NICU'} /></td><td className="px-4 py-3 text-sm">{toTitle(row.inquiry_type)}</td><td className="px-4 py-3 text-sm">{formatDate(row.requested_at)}</td><td className="px-4 py-3"><StatusBadge value={toTitle(row.status)} /></td><td className="px-4 py-3"><button onClick={() => void advance(row)} className="text-xs text-[#eea4bb]">Advance</button></td></tr>)}</tbody></table></div>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40"><form onSubmit={save} className="w-full max-w-md bg-white rounded-xl p-6 space-y-4"><div className="flex justify-between"><h2 className="font-semibold">Log Inquiry</h2><button type="button" onClick={() => setOpen(false)}><X className="w-4 h-4" /></button></div><select name="beneficiary_id" required className="w-full border rounded-lg px-3 py-2">{beneficiaries.map((b) => <option key={b.id} value={b.id}>{b.guardian_name} - {b.baby_name}{b.nicu_eligible ? ' (NICU)' : ''}</option>)}</select><select name="inquiry_type" className="w-full border rounded-lg px-3 py-2"><option value="walk_in">Walk-in</option><option value="hotline_call">Hotline Call</option></select><textarea name="notes" className="w-full border rounded-lg px-3 py-2" placeholder="Notes" /><button className="w-full rounded-lg py-2 text-white" style={{ background: '#eea4bb' }}>Save Inquiry</button></form></div>}
  </div>
}