import { useEffect, useMemo, useState } from 'react'
import { Plus, Search, X } from 'lucide-react'
import { PageHeader } from '../shared/PageHeader'
import { StatusBadge } from '../shared/StatusBadge'
import { supabase } from '../../../lib/supabase'

type Recipient = { id: string; guardian_name: string; baby_name: string; hospital: string | null; nicu_eligible: boolean; contact_number: string | null; contact_email: string | null; age_of_baby_days: number | null }
export function RecipientManagementScreen() {
  const [rows, setRows] = useState<Recipient[]>([]); const [search, setSearch] = useState(''); const [open, setOpen] = useState(false)
  async function load(): Promise<void> { const { data } = await supabase.from('beneficiaries').select('*').order('created_at', { ascending: false }); setRows((data ?? []) as Recipient[]) }
  useEffect(() => { void load() }, [])
  const filtered = useMemo(() => rows.filter((r) => [r.guardian_name, r.baby_name, r.hospital].join(' ').toLowerCase().includes(search.toLowerCase())), [rows, search])
  async function save(event: React.FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const form = new FormData(event.currentTarget); await supabase.from('beneficiaries').insert({ guardian_name: String(form.get('guardian_name')), baby_name: String(form.get('baby_name')), hospital: String(form.get('hospital')), contact_number: String(form.get('contact_number')), contact_email: String(form.get('contact_email') || '').toLowerCase() || null, nicu_eligible: form.get('nicu_eligible') === 'on', age_of_baby_days: Number(form.get('age_of_baby_days') || 0) }); setOpen(false); await load() }
  return <div><PageHeader crumbs={[{ label: 'Recipients' }]} title="Recipient Management" subtitle="Supabase-backed milk beneficiaries" actions={<button onClick={() => setOpen(true)} className="flex items-center gap-2 px-4 py-2 text-sm text-white rounded-lg" style={{ background: '#eea4bb' }}><Plus className="w-4 h-4" />Add Recipient</button>} />
    <div className="bg-white rounded-2xl border p-4 mb-4"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4" /><input value={search} onChange={(e) => setSearch(e.target.value)} className="w-full pl-9 pr-3 py-2 border rounded-lg" placeholder="Search recipient..." /></div></div>
    <div className="bg-white rounded-2xl border overflow-x-auto"><table className="w-full"><thead><tr>{['Guardian','Baby','Hospital','NICU','Contact','AOB Days'].map((h) => <th key={h} className="px-4 py-3 text-left text-xs text-[#6B7280]">{h}</th>)}</tr></thead><tbody>{filtered.map((r) => <tr key={r.id} className="border-t"><td className="px-4 py-3 text-sm">{r.guardian_name}</td><td className="px-4 py-3 text-sm">{r.baby_name}</td><td className="px-4 py-3 text-sm">{r.hospital}</td><td className="px-4 py-3"><StatusBadge value={r.nicu_eligible ? 'NICU' : 'Non-NICU'} /></td><td className="px-4 py-3 text-sm">{r.contact_number ?? r.contact_email}</td><td className="px-4 py-3 text-sm">{r.age_of_baby_days}</td></tr>)}</tbody></table></div>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40"><form onSubmit={save} className="w-full max-w-md bg-white rounded-xl p-6 space-y-4"><div className="flex justify-between"><h2 className="font-semibold">Add Recipient</h2><button type="button" onClick={() => setOpen(false)}><X className="w-4 h-4" /></button></div><input name="guardian_name" required className="w-full border rounded-lg px-3 py-2" placeholder="Guardian name" /><input name="baby_name" required className="w-full border rounded-lg px-3 py-2" placeholder="Baby name" /><input name="hospital" className="w-full border rounded-lg px-3 py-2" placeholder="Hospital" /><input name="contact_number" className="w-full border rounded-lg px-3 py-2" placeholder="Contact number" /><input name="contact_email" type="email" className="w-full border rounded-lg px-3 py-2" placeholder="Email" /><input name="age_of_baby_days" type="number" className="w-full border rounded-lg px-3 py-2" placeholder="Age of baby in days" /><label className="flex gap-2"><input name="nicu_eligible" type="checkbox" /> NICU eligible</label><button className="w-full rounded-lg py-2 text-white" style={{ background: '#eea4bb' }}>Save Recipient</button></form></div>}
  </div>
}